
  export const sample_foods = [
    {
      id: '1',
      name: 'CHICKEN BIRIYANI',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'https://img.freepik.com/premium-photo/juicy-chicken-biryani-with-smoke_303085-7807.jpg',
      tags: ['FASTFOOD', 'CHICKEN', 'RICE'],
    },
    {
      id: '2',
      name: 'EGG MASALA',
      price: 20,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'https://us.123rf.com/450wm/espies/espies2310/espies231000160/214549141-south-indian-style-egg-curry-recipe-close-up-in-a-plate-on-the-table.jpg?ver=6',
      tags: ['CURRY', 'Lunch'],
    },
    {
      id: '3',
      name: 'PANNER BUTTER MASALA',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'https://i.ytimg.com/vi/XSg921XEyuE/maxresdefault.jpg',
      tags: ['FASTFOOD', 'CURRY','VEG'],
    },
    {
      id: '4',
      name: 'NADAN CHICKEN CURRY',
      price: 2,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'https://images.slurrp.com/prod/articles/z53h1binha8.webp',
      tags: ['FASTFOOD', 'CURRY','CHICKEN'],
    },
    {
      id: '5',
      name: 'MUTTON BIRIYANI',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'https://img.freepik.com/premium-photo/delicious-hot-chicken-biryani-black-dish-dark-wooden-table-close-up-photography_5095-2079.jpg',
      tags: ['SlowFood', 'Soup','RICE'],
    },
    {
      id: '6',
      name: 'POROTTA',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'https://t4.ftcdn.net/jpg/02/00/16/83/360_F_200168344_q8hOT7OCE0GOoB8cTJFEGX4Ka1TArIHY.jpg',
      tags: ['FASTFOOD', 'BREADS', 'Lunch'],
    },
    {
      id: '7',
      name: 'FIRED RICE',
      price: 100,
      cookTime: '20-30',
      favorite: true,
      origins: [ 'NORTH INDIAN'],
      stars: 5,
      imageUrl: 'https://tfpj-s3.troisfoisparjour.com/app/uploads/2018/08/21084221/riz_frit_dinde_legumes_verts_l.jpg',
      tags: ['VEG','RICE'],
    },
  ];




  export const sample_tags = [
    { name: 'ALL', count: 6 },
    { name: 'FASTFOOD', count: 4 },
    { name: 'BREADS', count: 2 },
    { name: 'LUNCH', count: 3 },
    { name: 'CURRY', count: 2 },
    { name: 'CHICKEN', count: 1 },
    { name: 'RICE', count: 0 },
    { name: 'VEG', count: 1 },
  ];

  export const sample_users = [
    {
      id: 1,
      name: 'vishnu',
      email: 'vishnu@gmail.com',
      password: '12345',
      address: 'ottapalam',
      isAdmin: true,
    },
    {
      id: 2,
      name: 'shruthi',
      email: 'shruthi@gmail.com',
      password: '12345',
      address: 'palakkad',
      isAdmin: false,
    },
    {
      id: 3,
      name: 'jhon',
      email: 'jhon@gmail.com',
      password: '12345',
      address: 'kerala',
      isAdmin: false,
    },
  ];
